apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-page
  template:
    metadata:
      labels:
        app: status-page
    spec:
      containers:
        - name: status-page-app
          image: "{{ .Values.statusPageImage.repository }}:{{ .Values.statusPageImage.tag }}"
          ports:
            - containerPort: 8001
        - name: nginx
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001
  selector:
    app: status-page

